name: "D4vsLin's life"
favicon: null
layout_spectrum: 0.41099
typography_spectrum: 0.10508093191310763
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.1910922396928072
  lightness: 0.5
  saturation: 0.4230777940247208
  rhythmicContrast: 0.8765845578163862
purpose: []
