name: "D4vsLin's Blog"
favicon: null
layout_spectrum: 0.50017
typography_spectrum: 0.3484
title: Post about my everyday life
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-73841642-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#c7cddd'
    - '#6a86b6'
    - '#40629f'
  brandStrength: 0.3125
  lightness: 0.875
  saturation: 0.4230777940247208
  rhythmicContrast: 0.75
purpose: []
